ALTER TABLE `projects` ADD `project_url` text;
--> statement-breakpoint
INSERT INTO `projects` (`id`,`title`,`subtitle`,`category`,`year`,`brief`,`role`,`process`,`result`,`project_url`,`image_key`,`status`,`sort_order`,`created_at`,`updated_at`) VALUES
('ulis-eco','ULIS Eco','Sống xanh bắt đầu từ những thay đổi nhỏ trong cộng đồng sinh viên.','COMMUNITY PLATFORM','2026','Một nền tảng giúp sinh viên ULIS chia sẻ mẹo tái chế, trao đổi đồ dùng cũ và kết nối quanh lối sống bền vững.','Thiết kế UI/UX, định hướng hình ảnh và phát triển website.','Phân tích vấn đề lãng phí trong trường học → xây dựng kiến trúc nội dung → thiết kế giao diện → hoàn thiện trải nghiệm responsive.','Website truyền tải rõ câu chuyện sống xanh và tạo điểm chạm trực quan cho hoạt động cộng đồng.','https://uliseco.framer.website/about','/projects/ulis-eco.png','published',1,'2026-09-06T00:00:00.000Z','2026-09-06T00:00:00.000Z'),
('urun-be-uliser','U-RUN — Be ULISer, Be Runner','Đường đua số dành riêng cho cộng đồng sinh viên ULIS.','CAMPAIGN WEBSITE','2026','Giải chạy trực tuyến cần một website trẻ trung để giới thiệu hình thức tham gia, bộ race kit và tinh thần vận động của sinh viên.','Thiết kế trải nghiệm, giao diện và phát triển website.','Xác định hành trình đăng ký → tổ chức nội dung chiến dịch → thiết kế hệ hình ảnh năng động → tối ưu trên nhiều màn hình.','Một landing page giàu năng lượng, giúp thông tin giải chạy dễ tiếp cận và thúc đẩy đăng ký.','https://urunbeuliser.framer.website/','/projects/urun-be-uliser.png','published',2,'2026-09-06T00:01:00.000Z','2026-09-06T00:01:00.000Z'),
('ulife','U-Life','Chăm sóc sức khỏe thể chất và tinh thần cho sinh viên ĐHQGHN.','HEALTH PRODUCT','2026','Sinh viên cần một hệ sinh thái theo dõi sức khỏe toàn diện, giúp nhận biết sớm căng thẳng, kiệt sức và các rủi ro trong học tập.','Nghiên cứu sản phẩm, thiết kế UI/UX và phát triển website giới thiệu.','Tổng hợp vấn đề người dùng → định hình tính năng → xây dựng luồng trải nghiệm → thiết kế hệ thống giao diện sức khỏe thân thiện.','Concept sản phẩm kết nối theo dõi thể chất, tinh thần và hỗ trợ xây dựng thói quen tích cực.','https://ulife.framer.website/','/projects/ulife.png','published',3,'2026-09-06T00:02:00.000Z','2026-09-06T00:02:00.000Z'),
('wulis','WULIS — Workshop ULIS','Một điểm đến tập trung cho workshop và sự kiện học thuật.','EDTECH PLATFORM','2026','Thông tin workshop tại ULIS phân tán trên nhiều kênh khiến sinh viên thường bỏ lỡ cơ hội học tập phù hợp.','Thiết kế sản phẩm, UI/UX và phát triển giao diện.','Nghiên cứu nhu cầu tìm sự kiện → phân loại nội dung → xây dựng luồng khám phá → thiết kế và thử nghiệm giao diện.','Nền tảng tổng hợp workshop theo khoa và chủ đề, giúp sinh viên tìm cơ hội phát triển nhanh hơn.','https://wulis.framer.website/','/projects/wulis.png','published',4,'2026-09-06T00:03:00.000Z','2026-09-06T00:03:00.000Z'),
('the-book-bridge','The BookBridge','Cầu nối giáo trình đáng tin cậy cho cộng đồng ULIS.','COMMUNITY MARKETPLACE','2025','Giáo trình còn giá trị thường bị bỏ quên trong khi tân sinh viên gặp áp lực chi phí và khó tìm nguồn tài liệu đáng tin cậy.','Xây dựng concept, thiết kế visual và phát triển website.','Định nghĩa giá trị cộng đồng → thiết kế hành trình trao đổi → xây dựng ngôn ngữ minh họa → triển khai landing page.','Một nền tảng kể câu chuyện rõ ràng về việc kết nối sách cũ với người đang cần chúng.','https://thebookbridge.framer.website/','/projects/the-book-bridge.png','published',5,'2026-09-06T00:04:00.000Z','2026-09-06T00:04:00.000Z'),
('ulis-lost-found','ULIS Lost & Found','Nơi đồ thất lạc tìm đường về, đồ cũ bắt đầu hành trình mới.','COMMUNITY SERVICE','2026','Các bài tìm đồ thường trôi trên mạng xã hội, còn việc trao đổi đồ cũ giữa sinh viên thiếu một nơi tập trung và đáng tin cậy.','Thiết kế trải nghiệm, art direction và phát triển website.','Quan sát hành vi cộng đồng → nhóm các nhu cầu chính → xây dựng cấu trúc tìm và trao đổi → thiết kế giao diện giàu cá tính.','Một trải nghiệm kết nối hoạt động tìm đồ, trao đổi đồ cũ và tinh thần chia sẻ bền vững.','https://ulislostandfound.framer.website/','/projects/ulis-lost-found.png','published',6,'2026-09-06T00:05:00.000Z','2026-09-06T00:05:00.000Z'),
('orbits-defi','Orbits DeFi','Cánh cửa trực quan bước vào tài chính phi tập trung.','FINTECH LANDING PAGE','2026','Sản phẩm DeFi cần một hình ảnh hiện đại, đáng tin và dễ tiếp cận hơn với người dùng mới.','Thiết kế UI, motion direction và phát triển landing page.','Xây dựng thông điệp → thiết kế hệ thống thị giác tối giản → tạo chuyển động nhấn mạnh lợi ích → tối ưu trải nghiệm responsive.','Landing page đậm chất công nghệ với hệ màu tối, ánh sáng và nhịp chuyển động tập trung vào chuyển đổi.','https://orbitsdefi.framer.website/','/projects/orbits-defi.png','published',7,'2026-09-06T00:06:00.000Z','2026-09-06T00:06:00.000Z'),
('beetls','BeeTools','Kho công cụ AI và tiện ích được tuyển chọn cho công việc hằng ngày.','WEB APPLICATION','2026','Người dùng cần một nơi có cấu trúc rõ ràng để tìm kiếm, phân loại và lưu lại những công cụ AI phù hợp.','Thiết kế sản phẩm và phát triển ứng dụng web.','Thiết kế hệ phân loại → xây dựng tìm kiếm và bộ lọc → phát triển dashboard → hoàn thiện trạng thái tương tác và responsive.','Ứng dụng thư viện công cụ với tìm kiếm nhanh, danh mục, yêu thích và giao diện tối nhất quán.','https://beetls.vercel.app/','/projects/beetls.png','published',8,'2026-09-06T00:07:00.000Z','2026-09-06T00:07:00.000Z'),
('temsy','Temsy','Biến từng khoảnh khắc thành một con tem kỷ niệm.','DIGITAL COLLECTIBLES','2026','Một trải nghiệm sưu tầm cần biến ảnh cá nhân thành vật phẩm số có cảm xúc, dễ lưu giữ và khám phá.','Thiết kế sản phẩm, giao diện và phát triển ứng dụng.','Định hình concept tem số → xây dựng luồng tạo và khám phá → thiết kế hệ thống thẻ → phát triển trải nghiệm đa thiết bị.','Ứng dụng sưu tầm tem kỹ thuật số với không gian khám phá tối giản và gần gũi.','https://temsy.vercel.app/','/projects/temsy.png','published',9,'2026-09-06T00:08:00.000Z','2026-09-06T00:08:00.000Z'),
('arcade-school','Arcade Học Đường','Biến tiết học thành một sân chơi tương tác kiểu arcade.','EDTECH GAME','2026','Giáo viên cần công cụ tạo hoạt động trực tiếp giúp học sinh tham gia bài học hào hứng hơn ngay trong lớp.','Thiết kế trải nghiệm trò chơi và phát triển ứng dụng web.','Xây dựng cơ chế phòng học → thiết kế giao diện pixel art → phát triển luồng kết nối và mini game → kiểm tra trải nghiệm trình chiếu.','Một lớp học tương tác theo thời gian thực với mã phòng, vòng quay may mắn và ngôn ngữ arcade vui nhộn.','https://arcadeschool.vercel.app/index.html','/projects/arcade-school.png','published',10,'2026-09-06T00:09:00.000Z','2026-09-06T00:09:00.000Z')
ON CONFLICT(`id`) DO UPDATE SET `title`=excluded.`title`,`subtitle`=excluded.`subtitle`,`category`=excluded.`category`,`year`=excluded.`year`,`brief`=excluded.`brief`,`role`=excluded.`role`,`process`=excluded.`process`,`result`=excluded.`result`,`project_url`=excluded.`project_url`,`image_key`=excluded.`image_key`,`status`=excluded.`status`,`sort_order`=excluded.`sort_order`,`updated_at`=excluded.`updated_at`;
